name: "Flake.lock: update Nix dependencies"
on:
  workflow_dispatch:
  schedule:
    - cron: '0 6 * * *'

jobs:
  update-dependencies:
    permissions:
      contents: write
      id-token: write
      issues: write
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v6
      - name: install nix
        uses: DeterminateSystems/determinate-nix-action@v3
      - name: update flake lock
        uses: DeterminateSystems/update-flake-lock@main
        with:
          pr-labels: |
            dependencies
            automated
